//==============================================================================
//  WARNING!!  This file is overwritten by the Block Styler while generating
//  the automation code. Any modifications to this file will be lost after
//  generating the code again.
//
//       Filename:  D:\NXOPEN\USER\Application\secondUI.hpp
//
//        This file was generated by the NX Block Styler
//        Created by: 观众
//              Version: NX 2306
//              Date: 07-14-2026  (Format: mm-dd-yyyy)
//              Time: 14:47
//
//==============================================================================

#ifndef SECONDUI_H_INCLUDED
#define SECONDUI_H_INCLUDED

//------------------------------------------------------------------------------
//These includes are needed for the following template code
//------------------------------------------------------------------------------
#include <uf_defs.h>
#include <iostream>
#include <NXOpen/Session.hxx>
#include <NXOpen/UI.hxx>
#include <NXOpen/NXMessageBox.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/NXException.hxx>
#include <NXOpen/BlockStyler_UIBlock.hxx>
#include <NXOpen/BlockStyler_BlockDialog.hxx>
#include <NXOpen/BlockStyler_PropertyList.hxx>
#include <NXOpen/BlockStyler_Group.hxx>
#include <NXOpen/BlockStyler_Button.hxx>
#include <NXOpen/BlockStyler_SelectObject.hxx>
#include <NXOpen/BlockStyler_SpecifyPoint.hxx>
#include <NXOpen/BlockStyler_Enumeration.hxx>

// Additional NXOpen includes for feature creation
#include <NXOpen/Body.hxx>
#include <NXOpen/ListingWindow.hxx>
#include <NXOpen/Features_FeatureCollection.hxx>
#include <NXOpen/Features_Feature.hxx>
#include <NXOpen/Features_BlockFeatureBuilder.hxx>

// UF includes
#include <NXOpen/Part.hxx>
#include <NXOpen/PartCollection.hxx>
#include <NXOpen/Face.hxx>
#include <NXOpen/Edge.hxx>
#include <NXOpen/Update.hxx>

//------------------------------------------------------------------------------
//Bit Option for Property: SnapPointTypesEnabled
//------------------------------------------------------------------------------
#define              SnapPointTypesEnabled_UserDefined (1 << 0);

//------------------------------------------------------------------------------
// Namespaces needed for following template
//------------------------------------------------------------------------------
using namespace std;
using namespace NXOpen;
using namespace NXOpen::BlockStyler;

class DllExport secondUI
{
    // class members
public:
    static Session* theSession;
    static UI* theUI;
    secondUI();
    ~secondUI();
    NXOpen::BlockStyler::BlockDialog::DialogResponse Launch();

    // BlockStyler Callback Prototypes
    void initialize_cb();
    void dialogShown_cb();
    int apply_cb();
    int cancel_cb();
    int ok_cb();
    int update_cb(NXOpen::BlockStyler::UIBlock* block);
    PropertyList* GetBlockProperties(const char* blockID);

private:
    const char* theDlxFileName;
    NXOpen::BlockStyler::BlockDialog* theDialog;

    // Dialog controls
    NXOpen::BlockStyler::Group* group3;
    NXOpen::BlockStyler::Button* button0;    // Move
    NXOpen::BlockStyler::Button* button01;   // Execute Move/Copy
    NXOpen::BlockStyler::Group* group2;
    NXOpen::BlockStyler::SelectObject* selection0;  // Source body selection
    NXOpen::BlockStyler::Group* group1;
    NXOpen::BlockStyler::SpecifyPoint* point0;      // (unused)
    NXOpen::BlockStyler::Enumeration* enum0;         // Mode: Move/Copy
    int m_opMode;
    NXOpen::BlockStyler::Group* group;
    NXOpen::BlockStyler::SpecifyPoint* point01;      // Source point (optional)
    NXOpen::BlockStyler::Enumeration* enum01;        // Other mode (optional)

};
#endif //SECONDUI_H_INCLUDED