//==============================================================================

//  the automation code. Any modifications to this file will be lost after
//  generating the code again.
//
//       Filename:  D:\A NX FILE\Application\diancm.cpp
//
//        This file was generated by the NX Block UI Styler
//        Created by: 32645
//              Version: NX 2306
//              Date: 07-15-2026  (Format: mm-dd-yyyy)
//              Time: 09:50 (Format: hh-mm)
//
//==============================================================================
//==============================================================================
//  Implementation: 点选复制/移动对话框
//  Provides point-to-point translation move/copy via Block Styler dialog.
//  Architecture:
//    - Anonymous namespace for pure utility functions (geometry, transform)
//    - diancm class ties Block Styler callbacks to utility layer
//==============================================================================

#pragma warning(disable:4530)
#pragma execution_character_set("utf-8")

#include <uf.h>
#include <NXOpen/Features_MoveObjectBuilder.hxx>
#include <NXOpen/GeometricUtilities_ModlMotion.hxx>
#include <uf_modl.h>
#include <NXOpen/SelectNXObjectList.hxx>
#include <NXOpen/Features_BaseFeatureCollection.hxx>
#include <NXOpen/Direction.hxx>
#include <NXOpen/DirectionCollection.hxx>
#include <NXOpen/PointCollection.hxx>
// ModlTranslation.hxx unavailable in NX 2306, handled inline

#include <cmath>
#include <set>
#include <sstream>
#include <stdexcept>
#include <string>
#include <vector>

#include <windows.h>
#ifdef CreateDialog
#undef CreateDialog
#endif
#ifdef SelectObject
#undef SelectObject
#endif

#include <NXOpen/Session.hxx>
#include <NXOpen/UI.hxx>
#include <NXOpen/NXMessageBox.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/NXException.hxx>
#include <NXOpen/Part.hxx>
#include <NXOpen/PartCollection.hxx>
#include <NXOpen/Body.hxx>
#include <NXOpen/Face.hxx>
#include <NXOpen/Edge.hxx>
#include <NXOpen/NXObject.hxx>
#include <NXOpen/Update.hxx>
#include <NXOpen/WCS.hxx>

using namespace NXOpen;
using namespace NXOpen::BlockStyler;

#include "diancm.hpp"

//==============================================================================
//  Anonymous namespace — reusable utilities shared across the translation unit
//==============================================================================
namespace
{

//  Enums — mirror the DLX enumeration values set in Block Styler
enum class StartPointMode
{
    BodyCenterTop    = 0,
    BodyCenter       = 1,
    BodyCenterBottom = 2,
    FaceCenter       = 3
};

enum class FinishPointMode
{
    AbsOrigin  = 0,
    WcsOrigin  = 1,
    BodyCenter = 2,
    FaceCenter = 3,
    XZero      = 4,
    YZero      = 5,
    ZZero      = 6
};

//  DLX path resolution — look beside the DLL first, fall back to raw name
extern "C" IMAGE_DOS_HEADER __ImageBase;

std::string GetDllDirectory()
{
    char buffer[MAX_PATH] = {0};
    HMODULE module = reinterpret_cast<HMODULE>(&__ImageBase);
    DWORD length = GetModuleFileNameA(module, buffer, MAX_PATH);
    if (length == 0 || length >= MAX_PATH)
        return ".";

    std::string path(buffer);
    size_t slash = path.find_last_of("\\/");
    return slash == std::string::npos ? "." : path.substr(0, slash);
}

std::string ResolveDlxPath(const char* dlxName)
{
    std::string deployedPath = GetDllDirectory() + "\\" + dlxName;
    if (GetFileAttributesA(deployedPath.c_str()) != INVALID_FILE_ATTRIBUTES)
        return deployedPath;
    return dlxName;
}

//  Geometry helpers
double VectorLength(const Vector3d& v)
{
    return std::sqrt(v.X * v.X + v.Y * v.Y + v.Z * v.Z);
}

//  Tag resolution helpers
tag_t ResolveBodyTag(TaggedObject* obj)
{
    if (!obj) return NULL_TAG;

    if (auto* body = dynamic_cast<Body*>(obj))
        return body->Tag();
    if (auto* face = dynamic_cast<Face*>(obj))
    {
        Body* b = face->GetBody();
        return b ? b->Tag() : face->Tag();
    }
    if (auto* edge = dynamic_cast<Edge*>(obj))
    {
        Body* b = edge->GetBody();
        return b ? b->Tag() : edge->Tag();
    }
    return NULL_TAG;
}

//  Selection helpers
std::vector<NXOpen::Body*> CollectTransformBodies(BlockStyler::SelectObject* sel)
{
    std::vector<NXOpen::Body*> bodies;
    if (!sel) return bodies;

    std::set<tag_t> unique;
    for (auto* obj : sel->GetSelectedObjects())
    {
        tag_t t = ResolveBodyTag(obj);
        if (t != NULL_TAG && unique.insert(t).second)
            bodies.push_back(dynamic_cast<NXOpen::Body*>(obj));
    }
    return bodies;
}

TaggedObject* PrimarySelection(BlockStyler::SelectObject* sel)
{
    if (!sel) return nullptr;
    auto objects = sel->GetSelectedObjects();
    return objects.empty() ? nullptr : objects.front();
}

//  Point resolution

Point3d AskBoxCenter(tag_t objectTag)
{
    double box[6] = {0.0};
    int err = UF_MODL_ask_bounding_box(objectTag, box);
    if (err != 0)
    {
        std::ostringstream ss;
        ss << "读取包围盒失败，错误码 " << err;
        throw std::runtime_error(ss.str());
    }
    return Point3d((box[0] + box[3]) * 0.5,
                   (box[1] + box[4]) * 0.5,
                   (box[2] + box[5]) * 0.5);
}

Point3d AskBodyPoint(tag_t bodyTag, StartPointMode mode)
{
    double box[6] = {0.0};
    int err = UF_MODL_ask_bounding_box(bodyTag, box);
    if (err != 0)
    {
        std::ostringstream ss;
        ss << "读取体包围盒失败，错误码 " << err;
        throw std::runtime_error(ss.str());
    }

    double cx = (box[0] + box[3]) * 0.5;
    double cy = (box[1] + box[4]) * 0.5;
    switch (mode)
    {
        case StartPointMode::BodyCenterTop:
            return Point3d(cx, cy, box[5]);
        case StartPointMode::BodyCenterBottom:
            return Point3d(cx, cy, box[2]);
        default:
            return Point3d(cx, cy, (box[2] + box[5]) * 0.5);
    }
}

Point3d ResolveStartPoint(StartPointMode mode,
                          TaggedObject* primary,
                          BlockStyler::SpecifyPoint* manualPt)
{
    if (!primary)
        throw std::runtime_error("请先选择操作对象");

    if (mode == StartPointMode::FaceCenter)
    {
        if (auto* face = dynamic_cast<Face*>(primary))
            return AskBoxCenter(face->Tag());
        if (manualPt)
            return manualPt->Point();
        throw std::runtime_error("起始点为面中心时，请选择面或手动指定点");
    }

    tag_t bodyTag = ResolveBodyTag(primary);
    if (bodyTag == NULL_TAG)
        throw std::runtime_error("无法从选择对象解析体");
    return AskBodyPoint(bodyTag, mode);
}

Point3d ResolveFinishPoint(FinishPointMode mode,
                           TaggedObject* primary,
                           const Point3d& startPt,
                           Session* session,
                           BlockStyler::SpecifyPoint* manualPt)
{
    Part* workPart = session->Parts()->Work();

    switch (mode)
    {
        case FinishPointMode::AbsOrigin:
            return Point3d(0.0, 0.0, 0.0);

        case FinishPointMode::WcsOrigin:
            if (workPart && workPart->WCS())
                return workPart->WCS()->Origin();
            return Point3d(0.0, 0.0, 0.0);

        case FinishPointMode::BodyCenter:
        {
            if (!primary)
                throw std::runtime_error("结束点为体中心时，请选择操作对象");
            tag_t t = ResolveBodyTag(primary);
            return AskBoxCenter(t);
        }

        case FinishPointMode::FaceCenter:
        {
            if (auto* face = dynamic_cast<Face*>(primary))
            return AskBoxCenter(face->Tag());
            if (manualPt)
                return manualPt->Point();
            throw std::runtime_error("结束点为面中心时，请选择面或手动指定点");
        }

        case FinishPointMode::XZero:
            return Point3d(0.0, startPt.Y, startPt.Z);
        case FinishPointMode::YZero:
            return Point3d(startPt.X, 0.0, startPt.Z);
        case FinishPointMode::ZZero:
            return Point3d(startPt.X, startPt.Y, 0.0);

        default:
            throw std::runtime_error("未知的结束点模式");
    }
}

void ExecuteMoveCopy(const std::vector<NXOpen::Body*>& bodies,
                     const Point3d& startPt,
                     const Point3d& endPt,
                     bool isCopy)
{
    if (bodies.empty())
        throw std::runtime_error("请选择操作对象");

    if (VectorLength(Vector3d(endPt.X - startPt.X, endPt.Y - startPt.Y, endPt.Z - startPt.Z)) < 1.0e-9)
        throw std::runtime_error("起始点和结束点重合，不能执行零向量移动/复制");
    Session* session = Session::GetSession();
    Part* workPart = session->Parts()->Work();

    Features::MoveObjectBuilder* moveBuilder =
        workPart->BaseFeatures()->CreateMoveObjectBuilder(nullptr);

    try
    {
        moveBuilder->SetMoveObjectResult(isCopy ?
            Features::MoveObjectBuilder::MoveObjectResultOptionsCopyOriginal :
            Features::MoveObjectBuilder::MoveObjectResultOptionsMoveOriginal);

        for (auto* body : bodies)
            moveBuilder->ObjectToMoveObject()->Add(body);

        auto* motion = moveBuilder->TransformMotion();
        motion->SetOption(NXOpen::GeometricUtilities::ModlMotion::OptionsDeltaXyz);
        motion->SetDeltaEnum(NXOpen::GeometricUtilities::ModlMotion::DeltaReferenceAcsWorkPart);
        motion->SetDeltaX(endPt.X - startPt.X);
        motion->SetDeltaY(endPt.Y - startPt.Y);
        motion->SetDeltaZ(endPt.Z - startPt.Z);

        moveBuilder->Commit();
        moveBuilder->Destroy();
        moveBuilder = nullptr;
    }
    catch (const NXException&)
    {
        if (moveBuilder) moveBuilder->Destroy();
        throw;
    }
}

//  Point block helper — mark as Optional so user-click state is trackable
void SetPointOptional(NXOpen::BlockStyler::SpecifyPoint* ptBlock)
{
    if (!ptBlock) return;
    try
    {
        ptBlock->SetStepStatusAsString("Optional");
    }
    catch (...)
    {
    }
}

} // anonymous namespace

//==============================================================================
//  Static member initialization
//==============================================================================
Session* (diancm::theSession) = nullptr;
UI* (diancm::theUI) = nullptr;

//==============================================================================
//  Constructor
//==============================================================================
diancm::diancm()
    : m_opMode(OpMode::None), m_startPtSpecified(false), m_endPtSpecified(false)
{
   try
   {
        diancm::theSession = Session::GetSession();
       diancm::theUI = UI::GetUI();

        // static 保证 dlxPath 在 DLL 生命周期内不析构，c_str() 指针持久有效
        static std::string dlxPath = ResolveDlxPath("diancm.dlx");
        theDlxFileName = dlxPath.c_str();
        theDialog = diancm::theUI->CreateDialog(theDlxFileName);

        theDialog->AddApplyHandler(make_callback(this, &diancm::apply_cb));
        theDialog->AddOkHandler(make_callback(this, &diancm::ok_cb));
        theDialog->AddUpdateHandler(make_callback(this, &diancm::update_cb));
        theDialog->AddInitializeHandler(make_callback(this, &diancm::initialize_cb));
        theDialog->AddDialogShownHandler(make_callback(this, &diancm::dialogShown_cb));
    }
    catch (const exception& ex)
    {
        throw;
    }
}

//==============================================================================
//  Destructor
//==============================================================================
diancm::~diancm()
{
    if (theDialog != nullptr)
    {
        delete theDialog;
        theDialog = nullptr;
    }
}

//==============================================================================
//  Entry point
//==============================================================================
extern "C" DllExport void ufusr(char* param, int* retcod, int param_len)
{
    UF_initialize();
    diancm* app = nullptr;
    try
    {
        app = new diancm();
        app->Launch();
    }
    catch (const exception& ex)
    {
        diancm::theUI->NXMessageBox()->Show(
            "Block Styler", NXMessageBox::DialogTypeError, ex.what());
    }
    delete app;
    UF_terminate();
}

extern "C" DllExport int ufusr_ask_unload()
{
    return static_cast<int>(Session::LibraryUnloadOptionImmediately);
}

extern "C" DllExport void ufusr_cleanup(void)
{
    // 预留清理入口，当前无清理操作
}

//==============================================================================
//  Launch
//==============================================================================
BlockDialog::DialogResponse diancm::Launch()
{
    auto response = BlockDialog::DialogResponseInvalid;
    try
    {
        response = theDialog->Launch();
    }
    catch (const exception& ex)
    {
        diancm::theUI->NXMessageBox()->Show(
            "Block Styler", NXMessageBox::DialogTypeError, ex.what());
    }
    return response;
}

//==============================================================================
//  Callbacks
//==============================================================================

//  initialize_cb — bind UI blocks to member pointers
void diancm::initialize_cb()
{
    try
    {
        group0      = dynamic_cast<NXOpen::BlockStyler::Group*>(theDialog->TopBlock()->FindBlock("group0"));
        button0     = dynamic_cast<NXOpen::BlockStyler::Button*>(theDialog->TopBlock()->FindBlock("button0"));
        button01    = dynamic_cast<NXOpen::BlockStyler::Button*>(theDialog->TopBlock()->FindBlock("button01"));
        group       = dynamic_cast<NXOpen::BlockStyler::Group*>(theDialog->TopBlock()->FindBlock("group"));
        selection0  = dynamic_cast<NXOpen::BlockStyler::SelectObject*>(theDialog->TopBlock()->FindBlock("selection0"));
        group2      = dynamic_cast<NXOpen::BlockStyler::Group*>(theDialog->TopBlock()->FindBlock("group2"));
        point0      = dynamic_cast<NXOpen::BlockStyler::SpecifyPoint*>(theDialog->TopBlock()->FindBlock("point0"));
        enum0       = dynamic_cast<NXOpen::BlockStyler::Enumeration*>(theDialog->TopBlock()->FindBlock("enum0"));
        group3      = dynamic_cast<NXOpen::BlockStyler::Group*>(theDialog->TopBlock()->FindBlock("group3"));
        point01     = dynamic_cast<NXOpen::BlockStyler::SpecifyPoint*>(theDialog->TopBlock()->FindBlock("point01"));
        enum01      = dynamic_cast<NXOpen::BlockStyler::Enumeration*>(theDialog->TopBlock()->FindBlock("enum01"));
        toggle0      = dynamic_cast<NXOpen::BlockStyler::Toggle*>(theDialog->TopBlock()->FindBlock("toggle0"));
        // Mark point blocks as Optional for manual override tracking
        SetPointOptional(point0);
        SetPointOptional(point01);
        UpdateStartPointUI();

    }
    catch (const exception& ex)
    {
        diancm::theUI->NXMessageBox()->Show(
            "Block Styler", NXMessageBox::DialogTypeError, ex.what());
    }
}

//  dialogShown_cb
void diancm::dialogShown_cb()
{
    try
    {
        // any pre-launch UI setup
    }
    catch (const exception& ex)
    {
        diancm::theUI->NXMessageBox()->Show(
            "Block Styler", NXMessageBox::DialogTypeError, ex.what());
    }
}

//  update_cb — handle UI interactions
int diancm::update_cb(BlockStyler::UIBlock* block)
{
    try
    {
        if (block == button0)
        {
            m_opMode = OpMode::Move;
        }
        else if (block == button01)
        {
            m_opMode = OpMode::Copy;
        }
        else if (block == selection0)
        {
            UpdateStartPointUI();
        }
        else if (block == enum0)
        {
            // start point mode changed
        }
        else if (block == enum01)
        {
            // end point mode changed
        }
        else if (block == point0)
        {
            // point0 被点选——保留判断分支备查
        }
        else if (block == point01)
        {
            m_endPtSpecified = true;
        }
        else if (block == toggle0)
        {
            UpdateStartPointUI();
        }
    }
    catch (const exception& ex)
    {
        diancm::theUI->NXMessageBox()->Show(
            "Block Styler", NXMessageBox::DialogTypeError, ex.what());
    }
    return 0;
}

//  apply_cb — core logic: resolve points → execute transform
int diancm::apply_cb()
{
    int errorCode = 0;
    Session::UndoMarkId undoMark = theSession->SetUndoMark(
        Session::MarkVisibilityVisible, "点选择移动/复制");

    try
    {
        if (m_opMode == OpMode::None)
            throw std::runtime_error("请先点击「移动」或「复制」按钮选择操作模式");

        TaggedObject* primary = PrimarySelection(selection0);
        if (!primary)
            throw std::runtime_error("请选择操作对象");

        std::vector<NXOpen::Body*> selectedBodies = CollectTransformBodies(selection0);
        if (selectedBodies.empty())
            throw std::runtime_error("未选中有效体对象");

        // Resolve start point — manual point overrides enum mode
        Point3d start;
        if (m_startPtSpecified && point0)
        {
            start = point0->Point();
        }
        else
        {
            auto startMode = static_cast<StartPointMode>(GetEnumValue(enum0));
            start = ResolveStartPoint(startMode, primary, point0);
        }

        // Resolve end point — manual point overrides enum mode
        Point3d finish;
        if (m_endPtSpecified && point01)
        {
            finish = point01->Point();
        }
        else
        {
            auto finishMode = static_cast<FinishPointMode>(GetEnumValue(enum01));
            finish = ResolveFinishPoint(finishMode, primary, start, theSession, point01);
        }

        ExecuteMoveCopy(selectedBodies, start, finish,
                        m_opMode == OpMode::Copy);

        theSession->UpdateManager()->DoUpdate(undoMark);
    }
    catch (const NXException& ex)
    {
        errorCode = 1;
        theSession->UndoToMark(undoMark, "点选择移动/复制");
        diancm::theUI->NXMessageBox()->Show(
            "错误", NXMessageBox::DialogTypeError, ex.Message());
    }
    catch (const std::exception& ex)
    {
        errorCode = 1;
        theSession->UndoToMark(undoMark, "点选择移动/复制");
        diancm::theUI->NXMessageBox()->Show(
            "提示", NXMessageBox::DialogTypeInformation, ex.what());
    }

    return errorCode;
}

int diancm::ok_cb()
{
    return apply_cb();
}

//==============================================================================
//  PropertyList accessor
//==============================================================================
PropertyList* diancm::GetBlockProperties(const char* blockID)
{
    return theDialog->GetBlockProperties(blockID);
}

//  GetEnumValue — safe enumeration value extraction
int diancm::GetEnumValue(NXOpen::BlockStyler::Enumeration* enumBlock)
{
    if (!enumBlock) return 0;
    PropertyList* props = enumBlock->GetProperties();
    return props ? props->GetEnum("Value") : 0;
}

//  UpdateStartPointUI — enable/disable start point enum based on selection count
void diancm::UpdateStartPointUI()
{
    if (!selection0 || !enum0 || !point0 || !toggle0) return;

    bool multiEnabled = toggle0->Value();

    // Try to switch SelectMode at runtime
    try
    {
        PropertyList* props = selection0->GetProperties();
        props->SetEnum("SelectMode", multiEnabled ? 1 : 0);
    }
    catch (...) { }

    if (multiEnabled)
    {
        int count = static_cast<int>(selection0->GetSelectedObjects().size());
        if (count >= 2)
        {
            enum0->SetEnable(false);
            m_startPtSpecified = true;
        }
        else
        {
            enum0->SetEnable(true);
        }
    }
    else
    {
        enum0->SetEnable(true);
        m_startPtSpecified = false;
    }
}
