//==============================================================================
//  WARNING!!  This file is overwritten by the Block UI Styler while generating
//  the automation code. Any modifications to this file will be lost after
//  generating the code again.
//
//       Filename:  C:\A NX FILE\_Sourse\a2\a2.cpp
//
//        This file was generated by the NX Block UI Styler
//        Created by: 86136
//              Version: NX 2306
//              Date: 07-15-2026  (Format: mm-dd-yyyy)
//              Time: 15:59 (Format: hh-mm)
//
//==============================================================================

//==============================================================================
//  Purpose:  This TEMPLATE file contains C++ source to guide you in the
//  construction of your Block application dialog. The generation of your
//  dialog file (.dlx extension) is the first step towards dialog construction
//  within NX.  You must now create a NX Open application that
//  utilizes this file (.dlx).
//
//  The information in this file provides you with the following:
//
//  1.  Help on how to load and display your Block UI Styler dialog in NX
//      using APIs provided in NXOpen.BlockStyler namespace
//  2.  The empty callback methods (stubs) associated with your dialog items
//      have also been placed in this file. These empty methods have been
//      created simply to start you along with your coding requirements.
//      The method name, argument list and possible return values have already
//      been provided for you.
//==============================================================================

#pragma warning(disable:4530)
#pragma execution_character_set("utf-8")

//------------------------------------------------------------------------------
//These includes are needed for the following template code
//------------------------------------------------------------------------------
#include "a2.hpp"
using namespace NXOpen;
using namespace NXOpen::BlockStyler;

//------------------------------------------------------------------------------
// Helper function declarations
//------------------------------------------------------------------------------
namespace
{
    Session* g_session = nullptr;
    UI* g_ui = nullptr;
    Part* g_workPart = nullptr;

    double vectorLength(const Vector3d& vector)
    {
        return std::sqrt(vector.X * vector.X + vector.Y * vector.Y + vector.Z * vector.Z);
    }

    std::string statusText(int status)
    {
        switch (status)
        {
        case 0: return "成功";
        case 1: return "对象数量无效";
        case 2: return "变换参数无效";
        case 3: return "对象无效或不可变换";
        case 4: return "对象不支持当前矩阵";
        case 5: return "建模更新失败";
        case 6: return "复制实体添加建模数据失败";
        case 7: return "不能缩放参数化实体";
        case 8: return "变换矩阵不适用于对象";
        case 9: return "不能缩放展开曲线";
        case 10: return "不能镜像实体";
        case 11: return "不能变换装配 occurrence";
        case 12: return "不能变换草图或草图曲线";
        default: return "未知错误";
        }
    }

    Point3d askBoxCenter(tag_t objectTag)
    {
        double box[6] = {0.0};
        int errorCode = UF_MODL_ask_bounding_box(objectTag, box);
        if (errorCode != 0)
        {
            std::ostringstream ss;
            ss << "读取对象包围盒失败，错误码 " << errorCode;
            throw std::runtime_error(ss.str());
        }
        return Point3d((box[0] + box[3]) * 0.5, (box[1] + box[4]) * 0.5, (box[2] + box[5]) * 0.5);
    }

    Point3d askBodyPoint(tag_t bodyTag, StartPointMode mode)
    {
        double box[6] = {0.0};
        int errorCode = UF_MODL_ask_bounding_box(bodyTag, box);
        if (errorCode != 0)
        {
            std::ostringstream ss;
            ss << "读取体包围盒失败，错误码 " << errorCode;
            throw std::runtime_error(ss.str());
        }

        double x = (box[0] + box[3]) * 0.5;
        double y = (box[1] + box[4]) * 0.5;
        if (mode == StartPointMode::BodyCenterTop)
        {
            return Point3d(x, y, box[5]);
        }
        if (mode == StartPointMode::BodyCenterBottom)
        {
            return Point3d(x, y, box[2]);
        }
        return Point3d(x, y, (box[2] + box[5]) * 0.5);
    }

    tag_t resolveBodyTag(TaggedObject* object)
    {
        if (!object) return NULL_TAG;

        if (Body* body = dynamic_cast<Body*>(object))
            return body->Tag();
        if (Face* face = dynamic_cast<Face*>(object))
        {
            Body* body = face->GetBody();
            return body ? body->Tag() : face->Tag();
        }
        if (Edge* edge = dynamic_cast<Edge*>(object))
        {
            Body* body = edge->GetBody();
            return body ? body->Tag() : edge->Tag();
        }
        return object->Tag();
    }

    std::vector<tag_t> readSelectedTransformTags(BlockStyler::SelectObject* selectObject)
    {
        std::vector<tag_t> tags;
        if (!selectObject) return tags;

        std::set<tag_t> uniqueTags;
        std::vector<TaggedObject*> selectedObjects = selectObject->GetSelectedObjects();
        for (TaggedObject* object : selectedObjects)
        {
            tag_t tag = resolveBodyTag(object);
            if (tag != NULL_TAG && uniqueTags.insert(tag).second)
            {
                tags.push_back(tag);
            }
        }
        return tags;
    }

    TaggedObject* readPrimaryObject(BlockStyler::SelectObject* selectObject)
    {
        if (!selectObject) return nullptr;
        std::vector<TaggedObject*> selectedObjects = selectObject->GetSelectedObjects();
        return selectedObjects.empty() ? nullptr : selectedObjects.front();
    }

    int getEnumValue(BlockStyler::Enumeration* enumeration)
    {
        if (!enumeration) return 0;
        BlockStyler::PropertyList* properties = enumeration->GetProperties();
        return properties ? properties->GetEnum("Value") : 0;
    }

    void setPointOptional(BlockStyler::SpecifyPoint* pointBlock)
    {
        if (!pointBlock) return;
        try
        {
            pointBlock->SetStepStatusAsString("Optional");
        }
        catch (...)
        {
            // 旧 DLX 或 NX 版本不支持动态修改 StepStatus 时，继续让 DLX 自身属性生效
        }
    }

    Point3d resolveStartPoint(StartPointMode mode, TaggedObject* primaryObject, BlockStyler::SpecifyPoint* manualPoint)
    {
        if (!primaryObject)
            throw std::runtime_error("请选择操作对象");

        if (mode == StartPointMode::FaceCenter)
        {
            if (Face* face = dynamic_cast<Face*>(primaryObject))
                return askBoxCenter(face->Tag());
            if (manualPoint)
                return manualPoint->Point();
            throw std::runtime_error("起始点为面中心时，请选择面或指定点");
        }

        tag_t bodyTag = resolveBodyTag(primaryObject);
        if (bodyTag == NULL_TAG)
            throw std::runtime_error("无法从选择对象解析体中心");
        return askBodyPoint(bodyTag, mode);
    }

    Point3d resolveFinishPoint(FinishPointMode mode, TaggedObject* primaryObject, const Point3d& startPoint, BlockStyler::SpecifyPoint* manualPoint)
    {
        switch (mode)
        {
        case FinishPointMode::AbsOrigin:
            return Point3d(0.0, 0.0, 0.0);
        case FinishPointMode::WcsOrigin:
            if (g_workPart && g_workPart->WCS())
                return g_workPart->WCS()->Origin();
            return Point3d(0.0, 0.0, 0.0);
        case FinishPointMode::BodyCenter:
            if (!primaryObject)
                throw std::runtime_error("结束点为体中心时，请选择操作对象");
            return askBoxCenter(resolveBodyTag(primaryObject));
        case FinishPointMode::FaceCenter:
            if (Face* face = dynamic_cast<Face*>(primaryObject))
                return askBoxCenter(face->Tag());
            if (manualPoint)
                return manualPoint->Point();
            throw std::runtime_error("结束点为面中心时，请选择面或指定点");
        case FinishPointMode::XZero:
            return Point3d(0.0, startPoint.Y, startPoint.Z);
        case FinishPointMode::YZero:
            return Point3d(startPoint.X, 0.0, startPoint.Z);
        case FinishPointMode::ZZero:
            return Point3d(startPoint.X, startPoint.Y, 0.0);
        default:
            throw std::runtime_error("未知结束点枚举值");
        }
    }

    void executeMoveOrCopy(const std::vector<tag_t>& objectTags, const Vector3d& translation, OperationMode operationMode)
    {
        if (objectTags.empty())
            throw std::runtime_error("请选择操作对象");
        if (vectorLength(translation) < 1.0e-9)
            throw std::runtime_error("起始点和结束点重合，不能执行零向量移动/复制");

        if (operationMode == OperationMode::Move)
        {
            double matrix[16] = {
                1.0, 0.0, 0.0, translation.X,
                0.0, 1.0, 0.0, translation.Y,
                0.0, 0.0, 1.0, translation.Z,
                0.0, 0.0, 0.0, 1.0
            };

            std::vector<tag_t> entities = objectTags;
            int errorCode = UF_MODL_transform_entities(
                static_cast<int>(entities.size()), entities.data(), matrix);
            if (errorCode != 0)
            {
                std::ostringstream ss;
                ss << "移动失败，UF_MODL_transform_entities 错误码 " << errorCode;
                throw std::runtime_error(ss.str());
            }
            return;
        }

        // Copy operation
        double delta[3] = {translation.X, translation.Y, translation.Z};
        double matrix[12] = {0.0};
        uf5943(delta, matrix);

        int objectCount = static_cast<int>(objectTags.size());
        int moveOrCopy = 2;
        int destinationLayer = 0;
        int traceCurves = 2;
        int status = 0;
        tag_t traceCurveGroup = NULL_TAG;
        std::vector<tag_t> copies(objectTags.size(), NULL_TAG);

        uf5947(matrix, objectTags.data(), &objectCount, &moveOrCopy, &destinationLayer, &traceCurves,
               copies.data(), &traceCurveGroup, &status);
        if (status != 0)
        {
            std::ostringstream ss;
            ss << "复制失败，UF_TRNS 状态码 " << status << "：" << statusText(status);
            throw std::runtime_error(ss.str());
        }
    }
}

//------------------------------------------------------------------------------
// Initialize static variables
//------------------------------------------------------------------------------
Session *(a2::theSession) = NULL;
UI *(a2::theUI) = NULL;

//------------------------------------------------------------------------------
// Constructor for NX Styler class
//------------------------------------------------------------------------------
a2::a2()
{
    try
    {
        // Initialize the NX Open C++ API environment
        a2::theSession = NXOpen::Session::GetSession();
        a2::theUI = UI::GetUI();
        theDlxFileName = "a2.dlx";
        theDialog = a2::theUI->CreateDialog(theDlxFileName);
        // Registration of callback functions
        theDialog->AddApplyHandler(make_callback(this, &a2::apply_cb));
        theDialog->AddOkHandler(make_callback(this, &a2::ok_cb));
        theDialog->AddUpdateHandler(make_callback(this, &a2::update_cb));
        theDialog->AddInitializeHandler(make_callback(this, &a2::initialize_cb));
        theDialog->AddDialogShownHandler(make_callback(this, &a2::dialogShown_cb));
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        throw;
    }
}

//------------------------------------------------------------------------------
// Destructor for NX Styler class
//------------------------------------------------------------------------------
a2::~a2()
{
    if (theDialog != NULL)
    {
        delete theDialog;
        theDialog = NULL;
    }
}
//------------------------------- DIALOG LAUNCHING ---------------------------------
//
//    Before invoking this application one needs to open any part/empty part in NX
//    because of the behavior of the blocks.
//
//    Make sure the dlx file is in one of the following locations:
//        1.) From where NX session is launched
//        2.) $UGII_USER_DIR/application
//        3.) For released applications, using UGII_CUSTOM_DIRECTORY_FILE is highly
//            recommended. This variable is set to a full directory path to a file 
//            containing a list of root directories for all custom applications.
//            e.g., UGII_CUSTOM_DIRECTORY_FILE=$UGII_BASE_DIR\ugii\menus\custom_dirs.dat
//
//    You can create the dialog using one of the following way:
//
//    1. USER EXIT
//
//        1) Create the Shared Library -- Refer "Block UI Styler programmer's guide"
//        2) Invoke the Shared Library through File->Execute->NX Open menu.
//
//------------------------------------------------------------------------------
extern "C" DllExport void  ufusr(char *param, int *retcod, int param_len)
{
    a2 *thea2 = NULL;
    try
    {
        thea2 = new a2();
        // The following method shows the dialog immediately
        thea2->Launch();
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        a2::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
    if(thea2 != NULL)
    {
        delete thea2;
        thea2 = NULL;
    }
}

//------------------------------------------------------------------------------
// This method specifies how a shared image is unloaded from memory
// within NX. This method gives you the capability to unload an
// internal NX Open application or user  exit from NX. Specify any
// one of the three constants as a return value to determine the type
// of unload to perform:
//
//
//    Immediately : unload the library as soon as the automation program has completed
//    Explicitly  : unload the library from the "Unload Shared Image" dialog
//    AtTermination : unload the library when the NX session terminates
//
//
// NOTE:  A program which associates NX Open applications with the menubar
// MUST NOT use this option since it will UNLOAD your NX Open application image
// from the menubar.
//------------------------------------------------------------------------------
extern "C" DllExport int ufusr_ask_unload()
{
    //return (int)Session::LibraryUnloadOptionExplicitly;
    return (int)Session::LibraryUnloadOptionImmediately;
    //return (int)Session::LibraryUnloadOptionAtTermination;
}

//------------------------------------------------------------------------------
// Following method cleanup any housekeeping chores that may be needed.
// This method is automatically called by NX.
//------------------------------------------------------------------------------
extern "C" DllExport void ufusr_cleanup(void)
{
    try
    {
        //---- Enter your callback code here -----
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        a2::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
}

//------------------------------------------------------------------------------
//This method launches the dialog to screen
//------------------------------------------------------------------------------
NXOpen::BlockStyler::BlockDialog::DialogResponse a2::Launch()
{
    NXOpen::BlockStyler::BlockDialog::DialogResponse dialogResponse= NXOpen::BlockStyler::BlockDialog::DialogResponse::DialogResponseInvalid;
    try
    {
        dialogResponse=theDialog->Launch();
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        a2::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
    return dialogResponse;
}

//------------------------------------------------------------------------------
//---------------------Block UI Styler Callback Functions--------------------------
//------------------------------------------------------------------------------

//------------------------------------------------------------------------------
//Callback Name: initialize_cb
//------------------------------------------------------------------------------
void a2::initialize_cb()
{
    try
    {
        UF_initialize();

        group0 = dynamic_cast<NXOpen::BlockStyler::Group*>(theDialog->TopBlock()->FindBlock("group0"));
        button0 = dynamic_cast<NXOpen::BlockStyler::Button*>(theDialog->TopBlock()->FindBlock("button0"));
        button01 = dynamic_cast<NXOpen::BlockStyler::Button*>(theDialog->TopBlock()->FindBlock("button01"));
        group = dynamic_cast<NXOpen::BlockStyler::Group*>(theDialog->TopBlock()->FindBlock("group"));
        selection0 = dynamic_cast<NXOpen::BlockStyler::SelectObject*>(theDialog->TopBlock()->FindBlock("selection0"));
        toggle0 = dynamic_cast<NXOpen::BlockStyler::Toggle*>(theDialog->TopBlock()->FindBlock("toggle0"));
        group1 = dynamic_cast<NXOpen::BlockStyler::Group*>(theDialog->TopBlock()->FindBlock("group1"));
        point0 = dynamic_cast<NXOpen::BlockStyler::SpecifyPoint*>(theDialog->TopBlock()->FindBlock("point0"));
        enum0 = dynamic_cast<NXOpen::BlockStyler::Enumeration*>(theDialog->TopBlock()->FindBlock("enum0"));
        group2 = dynamic_cast<NXOpen::BlockStyler::Group*>(theDialog->TopBlock()->FindBlock("group2"));
        point01 = dynamic_cast<NXOpen::BlockStyler::SpecifyPoint*>(theDialog->TopBlock()->FindBlock("point01"));
        enum01 = dynamic_cast<NXOpen::BlockStyler::Enumeration*>(theDialog->TopBlock()->FindBlock("enum01"));

        // 设置手动点块为可选
        setPointOptional(point0);
        setPointOptional(point01);

        UF_terminate();
    }
    catch(exception& ex)
    {
        UF_terminate();
        a2::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
}

//------------------------------------------------------------------------------
//Callback Name: dialogShown_cb
//This callback is executed just before the dialog launch. Thus any value set 
//here will take precedence and dialog will be launched showing that value. 
//------------------------------------------------------------------------------
void a2::dialogShown_cb()
{
    try
    {
        UF_initialize();

        // 初始状态：toggle0 未选中 = 单选
        toggle0->SetValue(false);

        // 同步设置 selection0 为单选模式
        BlockStyler::PropertyList* selectionProps = selection0->GetProperties();
        if (selectionProps)
        {
            selectionProps->SetLogical("AllowMultipleSelection", false);
            delete selectionProps;
        }

        UF_terminate();
    }
    catch(exception& ex)
    {
        UF_terminate();
        a2::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
}

//------------------------------------------------------------------------------
//Callback Name: apply_cb
//------------------------------------------------------------------------------
int a2::apply_cb()
{
    int errorCode = 0;
    try
    {
        g_session = theSession;
        g_ui = theUI;
        g_workPart = g_session->Parts()->Work();

        if (!executeFromDialog())
            errorCode = 1;
    }
    catch(exception& ex)
    {
        errorCode = 1;
        a2::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
    return errorCode;
}

//------------------------------------------------------------------------------
//Callback Name: update_cb
//------------------------------------------------------------------------------
int a2::update_cb(NXOpen::BlockStyler::UIBlock* block)
{
    try
    {
        if(block == button0)
        {
            // 点击"移动"按钮
            m_operationMode = OperationMode::Move;
            theSession->ListingWindow()->Open();
            theSession->ListingWindow()->WriteLine("已选择移动模式");
        }
        else if(block == button01)
        {
            // 点击"复制"按钮
            m_operationMode = OperationMode::Copy;
            theSession->ListingWindow()->Open();
            theSession->ListingWindow()->WriteLine("已选择复制模式");
        }
        else if(block == selection0)
        {
            // 选择操作对象 — 获取当前已选对象数量
            std::vector<TaggedObject*> selected = selection0->GetSelectedObjects();
            theSession->ListingWindow()->Open();
            theSession->ListingWindow()->WriteLine("已选择 " + std::to_string(selected.size()) + " 个对象");
        }
        else if(block == toggle0)
        {
            // 切换单选/多选模式
            UF_initialize();

            bool isMultiSelect = toggle0->Value();
            BlockStyler::PropertyList* selectionProps = selection0->GetProperties();
            if (selectionProps)
            {
                selectionProps->SetLogical("AllowMultipleSelection", isMultiSelect);
                delete selectionProps;
            }

            theSession->ListingWindow()->Open();
            theSession->ListingWindow()->WriteLine(
                isMultiSelect ? "已切换为多选模式，可同时选择多个对象" : "已切换为单选模式，每次只能选择一个对象");

            UF_terminate();
        }
        else if(block == point0)
        {
            // 手动指定起点 — 无特殊逻辑
        }
        else if(block == enum0)
        {
            // 起点模式切换
            int mode = getEnumValue(enum0);
            theSession->ListingWindow()->Open();
            theSession->ListingWindow()->WriteLine("起点模式已切换，当前值: " + std::to_string(mode));
        }
        else if(block == point01)
        {
            // 手动指定终点 — 无特殊逻辑
        }
        else if(block == enum01)
        {
            // 终点模式切换
            int mode = getEnumValue(enum01);
            theSession->ListingWindow()->Open();
            theSession->ListingWindow()->WriteLine("终点模式已切换，当前值: " + std::to_string(mode));
        }
    }
    catch(exception& ex)
    {
        a2::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
    return 0;
}

//------------------------------------------------------------------------------
//Callback Name: ok_cb
//------------------------------------------------------------------------------
int a2::ok_cb()
{
    int errorCode = 0;
    try
    {
        g_session = theSession;
        g_ui = theUI;
        g_workPart = g_session->Parts()->Work();

        if (!executeFromDialog())
            errorCode = 1;
    }
    catch(exception& ex)
    {
        errorCode = 1;
        a2::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
    return errorCode;
}

//------------------------------------------------------------------------------
//Function Name: GetBlockProperties
//Description: Returns the propertylist of the specified BlockID
//------------------------------------------------------------------------------
PropertyList* a2::GetBlockProperties(const char *blockID)
{
    return theDialog->GetBlockProperties(blockID);
}

//------------------------------------------------------------------------------
// Function Name: executeFromDialog
// Description: 从对话框读取参数并执行移动/复制操作
//------------------------------------------------------------------------------
bool a2::executeFromDialog()
{
    Session::UndoMarkId undoMark = theSession->SetUndoMark(
        Session::MarkVisibilityVisible, "点到点移动与复制");

    try
    {
        if (m_operationMode == OperationMode::None)
            throw std::runtime_error("请先点击「移动」或「复制」按钮选择操作模式");

        // 读取所选对象
        TaggedObject* primaryObject = readPrimaryObject(selection0);
        std::vector<tag_t> selectedTags = readSelectedTransformTags(selection0);

        if (!primaryObject || selectedTags.empty())
            throw std::runtime_error("请选择操作对象");

        // 读取起点模式与终点模式
        StartPointMode startMode = static_cast<StartPointMode>(getEnumValue(enum0));
        FinishPointMode finishMode = static_cast<FinishPointMode>(getEnumValue(enum01));

        // 解析起点和终点
        Point3d start = resolveStartPoint(startMode, primaryObject, point0);
        Point3d finish = resolveFinishPoint(finishMode, primaryObject, start, point01);

        // 计算位移向量
        Vector3d translation(finish.X - start.X, finish.Y - start.Y, finish.Z - start.Z);

        // 执行移动或复制
        executeMoveOrCopy(selectedTags, translation, m_operationMode);

        // 更新建模
        if (theSession && theSession->UpdateManager())
            theSession->UpdateManager()->DoUpdate(undoMark);

        // 信息输出
        theSession->ListingWindow()->Open();
        theSession->ListingWindow()->WriteLine(
            std::string(m_operationMode == OperationMode::Move ? "移动" : "复制") +
            "完成，操作对象数: " + std::to_string(selectedTags.size()));

        UF_DISP_refresh();
        return true;
    }
    catch (const NXException& ex)
    {
        theSession->UndoToMark(undoMark, "点到点移动与复制");
        a2::theUI->NXMessageBox()->Show("错误", NXOpen::NXMessageBox::DialogTypeError, ex.Message());
    }
    catch (const std::exception& ex)
    {
        theSession->UndoToMark(undoMark, "点到点移动与复制");
        a2::theUI->NXMessageBox()->Show("错误", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
    return false;
}
